### PR TITLE
EVG-6312 Make text of expandable lobster lines unselectable

### PR DESCRIPTION
**Pull request by vessy-mongodb**
This lets you copy blocks of lines that include expandable rows without also copying over the text of the expandable rows. 

Example:

line 1
line 2
~ ~ 10 lines skipped. Expand: All, Five ~ ~ ~
line 3
line 4

becomes

line 1
line 2
line 3
line 4

Equivalent to hiding expandable rows before selecting your text.

### CODE REVIEW

**Comment by john-m-liu** [comment]
Are you sure we want the text to be unselectable though? It seems useful to know when log output has been skipped

**Comment by vessy-mongodb** [comment]
Fair point. I'll work on making just the "n lines skipped" part selectable.

**Comment by vessy-mongodb** [comment]
The example would now look like:

line 1
line 2
10 lines skipped.
line 3
line 4

Let me know if you want me to make further improvements.

**Comment by vessy-mongodb** [comment]
lines-skipped

**Pull request merged**
